[project]
name = "pyspark-cr7"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.7"
dependencies = [
    "click>=8.3.0",
    "pyspark>=4.0.1",
]
